package com.cdodi.webidl.backend

import com.cdodi.webidl.model.Descriptor
import com.cdodi.webidl.model.InterfaceMember
import com.squareup.kotlinpoet.CodeBlock

/**
 * KDoc for generated declarations: what the IDL's extended attributes mean for the caller, and a link into the spec.
 *
 * Anchors follow Bikeshed's naming, which the WebGPU spec uses: `#gpudevice`, `#dom-gpudevice-createbuffer`,
 * `#dictdef-...`, `#enumdef-...`, `#namespacedef-...`. A member's anchor is named after the definition that declares
 * it (`label` from the GPUObjectBase mixin is `#dom-gpuobjectbase-label` on every interface that includes it).
 */
class Docs(private val specUrl: String?) {

    fun forInterface(descriptor: Descriptor.InterfaceDescriptor): CodeBlock =
        if (descriptor.unionOf.isNotEmpty()) {
            // Generated by the compiler, not defined in the IDL: nothing to link to, so say what it stands for.
            build(null, listOf("A union: accepts ${descriptor.unionOf.joinToString { "[$it]" }}. Each of them extends this marker."))
        } else {
            build(link(descriptor.name.lowercase()), definitionNotes(descriptor.extendedAttributes))
        }

    fun forDictionary(descriptor: Descriptor.InterfaceDescriptor): CodeBlock =
        build(link("dictdef-" + descriptor.name.lowercase()), emptyList())

    fun forEnum(descriptor: Descriptor.EnumDescriptor): CodeBlock =
        build(link("enumdef-" + descriptor.name.lowercase()), emptyList())

    fun forNamespace(descriptor: Descriptor.InterfaceDescriptor): CodeBlock =
        build(link("namespacedef-" + descriptor.name.lowercase()), definitionNotes(descriptor.extendedAttributes))

    fun forMember(member: InterfaceMember): CodeBlock {
        val synthesized = (member as? InterfaceMember.VariableDescriptor)?.isSynthesized == true ||
            (member as? InterfaceMember.FunctionDescriptor)?.isSynthesized == true
        val owner = member.declaredIn
        val anchor = if (synthesized || owner == null || member.name == "constructor") null else "dom-${owner.lowercase()}-${member.name.lowercase()}"

        val notes = memberNotes(member.extendedAttributes) + when (member) {
            is InterfaceMember.VariableDescriptor -> typeNotes(member.type.extendedAttributes)
            else -> emptyList()
        }
        val parameters = (member as? InterfaceMember.FunctionDescriptor)?.parameters.orEmpty()
            .mapNotNull { param -> typeNotes(param.type.extendedAttributes).takeIf { it.isNotEmpty() }?.let { "@param ${param.name} ${it.joinToString(" ")}" } }

        return build(anchor?.let(::link), notes, parameters)
    }

    /** Dictionary factory: one @param line for each member whose type has range or clamping rules. */
    fun forFactory(descriptor: Descriptor.InterfaceDescriptor): CodeBlock {
        val parameters = descriptor.members.filterIsInstance<InterfaceMember.VariableDescriptor>()
            .mapNotNull { member -> typeNotes(member.type.extendedAttributes).takeIf { it.isNotEmpty() }?.let { "@param ${member.name} ${it.joinToString(" ")}" } }
        return build(link("dictdef-" + descriptor.name.lowercase()), emptyList(), parameters)
    }

    private fun link(anchor: String): String? = specUrl?.let { "[specification](${it.trimEnd('/')}/#$anchor)" }

    private fun build(link: String?, notes: List<String>, tags: List<String> = emptyList()): CodeBlock {
        val paragraphs = listOfNotNull(link?.let { "See the $it." }) + notes
        val text = (paragraphs + tags).joinToString("\n")
        return if (text.isEmpty()) CodeBlock.of("") else CodeBlock.of("%L\n", text)
    }

    private fun definitionNotes(attributes: List<String>): List<String> = attributes.mapNotNull { attribute ->
        when {
            attribute.startsWith("Exposed=") ->
                "Exposed to: ${attribute.removePrefix("Exposed=").removeSurrounding("(", ")").split(',').joinToString(", ")}."
            attribute == "SecureContext" -> "Only available in secure contexts (HTTPS)."
            else -> null
        }
    }

    private fun memberNotes(attributes: List<String>): List<String> = attributes.mapNotNull { attribute ->
        when (attribute) {
            "SameObject" -> "Always returns the same object (`[SameObject]`)."
            "NewObject" -> "Returns a new object every time (`[NewObject]`)."
            "SecureContext" -> "Only available in secure contexts (HTTPS)."
            else -> null
        }
    }

    private fun typeNotes(attributes: List<String>): List<String> = attributes.distinct().mapNotNull { attribute ->
        when (attribute) {
            "EnforceRange" -> "Throws a TypeError if the value is not finite or out of range (`[EnforceRange]`)."
            "Clamp" -> "Out-of-range values are clamped (`[Clamp]`)."
            else -> null
        }
    }
}
