package com.cdodi.webidl.model

sealed interface Descriptor {
    val name: String

    data class TypeDescriptor(
        override val name: String,
        val isNullable: Boolean = false,
        val unionMembers: List<TypeDescriptor> = emptyList(),
        val record: Map<TypeDescriptor, TypeDescriptor>? = null,
        val sequenceOf: TypeDescriptor? = null,
        val promiseOf: TypeDescriptor? = null,
        /** Extended attributes of the type or argument, e.g. EnforceRange, Clamp, AllowShared. */
        val extendedAttributes: List<String> = emptyList(),
    ) : Descriptor

    data class InterfaceDescriptor(
        override val name: String,
        val members: List<InterfaceMember>,
        val superTypes: Set<String>,
        /** e.g. Exposed=(Window,Worker), SecureContext. */
        val extendedAttributes: List<String> = emptyList(),
        /** For a union marker interface generated by the compiler: the types it stands for. Empty for IDL definitions. */
        val unionOf: List<String> = emptyList(),
    ) : Descriptor {
        val hasConstructor: Boolean
            get() = members.any { it.name == "constructor" }

        operator fun plus(other: InterfaceDescriptor?): InterfaceDescriptor {
            if (other == null) return this

            return copy(members = members + other.members, superTypes = superTypes + other.superTypes)
        }
    }

    data class EnumDescriptor(
        override val name: String,
        val values: List<String>,
        /** Marker interfaces of the unions this enum belongs to. */
        val superTypes: Set<String> = emptySet(),
    ) : Descriptor
}

sealed interface InterfaceMember : Descriptor {
    val extendedAttributes: List<String>

    /** The interface, mixin, partial, dictionary or namespace that declares it; spec anchors are named after it. */
    val declaredIn: String?

    fun withDeclaredIn(owner: String): InterfaceMember = when (this) {
        is VariableDescriptor -> copy(declaredIn = declaredIn ?: owner)
        is FunctionDescriptor -> copy(declaredIn = declaredIn ?: owner)
        is ConstantDescriptor -> copy(declaredIn = declaredIn ?: owner)
    }

    data class VariableDescriptor(
        override val name: String,
        val type: Descriptor.TypeDescriptor,
        val isReadonly: Boolean = false,
        /** Dictionary member marked `required`. */
        val isRequired: Boolean = false,
        /** Operation argument marked `optional`, with or without a default value. */
        val isOptional: Boolean = false,
        /** Operation argument declared with `...`. */
        val isVariadic: Boolean = false,
        val defaultValue: String? = null,
        override val extendedAttributes: List<String> = emptyList(),
        override val declaredIn: String? = null,
        /** Generated from a declaration such as setlike, so the spec has no anchor for it. */
        val isSynthesized: Boolean = false,
    ) : InterfaceMember

    data class FunctionDescriptor(
        override val name: String,
        val returnType: Descriptor.TypeDescriptor,
        val parameters: List<VariableDescriptor>,
        override val extendedAttributes: List<String> = emptyList(),
        override val declaredIn: String? = null,
        val isSynthesized: Boolean = false,
    ) : InterfaceMember

    data class ConstantDescriptor(
        override val name: String,
        val type: Descriptor.TypeDescriptor,
        val value: String,
        override val extendedAttributes: List<String> = emptyList(),
        override val declaredIn: String? = null,
    ) : InterfaceMember
}
